"""add click count to url

Revision ID: 9a8fa6020ef5
Revises: 1a6f22c8490f
Create Date: 2026-09-22 12:24:51.633525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8fa6020ef5'
down_revision: Union[str, Sequence[str], None] = '1a6f22c8490f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('click_count', sa.Integer(), nullable=True))
    op.alter_column('url', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('url', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'url', ['short_code'])
    op.drop_column('url', 'click_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('click_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'url', type_='unique')
    op.alter_column('url', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('url', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('url', 'click_count')
    # ### end Alembic commands ###
