"""custom code field

Revision ID: a0d0b0addb1b
Revises: e9ad8199bb5b
Create Date: 2026-09-23 10:27:25.435875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d0b0addb1b'
down_revision: Union[str, Sequence[str], None] = 'e9ad8199bb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('custom_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'custom_code')
    # ### end Alembic commands ###
