"""short_url field

Revision ID: e8d3aacb550b
Revises: 9a8fa6020ef5
Create Date: 2026-09-22 19:34:01.193814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d3aacb550b'
down_revision: Union[str, Sequence[str], None] = '9a8fa6020ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('short_url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'url', ['short_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_column('url', 'short_url')
    # ### end Alembic commands ###
