"""expires at

Revision ID: e9ad8199bb5b
Revises: e8d3aacb550b
Create Date: 2026-09-22 19:56:30.732861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ad8199bb5b'
down_revision: Union[str, Sequence[str], None] = 'e8d3aacb550b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'expires_at')
    # ### end Alembic commands ###
